Payments Updates
checkout/checkout-sdk-java pull request #274
Opened 2022-09-27 01:06 UTC by Armando-Ibarra

* Added Support for ALMA source (CS2)
* Added Support for One Klarna source (CS2)

2022-09-27 08:32 UTC, martinseco commented on src/main/java/com/checkout/payments/request/source/apm/RequestAlmaSource.java
> +public class RequestAlmaSource extends AbstractRequestSource {
Shouldn't this be a final class?

2022-09-27 08:45 UTC, martinseco commented on src/main/java/com/checkout/payments/request/source/apm/RequestPayPalSource.java
>  public class RequestPayPalSource extends AbstractRequestSource {
Same as in AlmaSource. This should be final class

2022-09-27 08:51 UTC, martinseco commented on src/test/java/com/checkout/payments/RequestApmPaymentsIT.java
> +            assertTrue(exception.getCause() instanceof CheckoutApiException);
Maybe we should validate the error message, so that we know that the exception is the one we are expecting?

2022-09-27 08:52 UTC, martinseco requested changes
Looks good! Some minor comments

2022-09-27 17:49 UTC, Armando-Ibarra commented on src/main/java/com/checkout/payments/request/source/apm/RequestAlmaSource.java
> +public class RequestAlmaSource extends AbstractRequestSource {
Correct, good call out

2022-09-28 11:09 UTC, martinseco approved these changes

2022-09-28 21:48 UTC, merged