Adds support for Financial Actions API
checkout/checkout-sdk-java pull request #310
Opened 2023-02-08 14:42 UTC by martinseco

2023-02-10 10:08 UTC, armandojaleo commented
Good job, LGTM! in the test only, if your query request is empty, does the request work?

2023-02-10 11:03 UTC, armandojaleo approved these changes

2023-02-13 02:38 UTC, Armando-Ibarra requested changes

2023-02-13 02:38 UTC, Armando-Ibarra commented on src/main/java/com/checkout/CheckoutApiImpl.java
> +import com.checkout.apm.ideal.IdealClient;
What's the purpose of this import?

2023-02-13 02:38 UTC, Armando-Ibarra commented on src/main/java/com/checkout/financial/ActionBreakdown.java
> +    private float fxRateApplied;
We don't use primitives here, we should use `Double` class

2023-02-13 02:38 UTC, Armando-Ibarra commented on src/main/java/com/checkout/financial/ActionBreakdown.java
> +    private float fxRateApplied;
Same for all in this class

2023-02-13 02:38 UTC, Armando-Ibarra commented on src/main/java/com/checkout/financial/FinancialAction.java
> +    @SerializedName("payment_id")
NIT: Please add a space between class and property

2023-02-13 02:38 UTC, Armando-Ibarra commented on src/main/java/com/checkout/financial/FinancialActionsQueryFilter.java
> +    @SerializedName("payment_id")
NIT: empty line

2023-02-13 02:38 UTC, Armando-Ibarra commented on src/main/java/com/checkout/financial/FinancialActionsQueryResponse.java
> +    private int count;
Please use Integer.

2023-02-13 02:38 UTC, Armando-Ibarra commented on src/main/java/com/checkout/financial/Region.java
> +    @SerializedName(value = "Domestic", alternate = {"DOMESTIC", "domestic"})
Is the alternate something that happens during deserialization? Otherwise, we should keep only the value that appears on API reference.

2023-02-13 02:38 UTC, Armando-Ibarra commented on src/test/java/com/checkout/financial/FinancialTestIT.java
> +    private PaymentResponse makeCardPayment() {
Any particular case for this method? Can't we reuse a method from AbstractPaymentsTestIT?

2023-02-14 15:37 UTC, Armando-Ibarra approved these changes

2023-02-14 16:08 UTC, merged